<div class="row">
<div class="col-xs-12">
	<h3 class="text-center">Revisión Técnica</h3>
</div>
	<div class="col-sm-6 col-xs-12">
		<?php echo Html::img('placeholder.png', 'producto', 'class="img-rounded"') ?>
		<h4>Descripción</h4>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer non turpis vitae justo mattis finibus. Praesent feugiat condimentum eros, quis imperdiet lacus laoreet ut. Quisque tempor magna neque, et blandit lacus dignissim id. Phasellus nibh quam, vestibulum in ultrices eu, luctus sed felis. Curabitur odio risus, pulvinar eu iaculis sed, maximus sed urna. Curabitur placerat felis sit amet velit mattis egestas et vel justo. Morbi quam lectus, vulputate eget hendrerit eu, eleifend eu nulla.</p>
	</div>
		<div class="col-sm-6 col-xs-12">
			<h4 class="text-center">Detalles del pedido</h4>
			<ul class="list-group">
				<li class="list-group-item"><b>Cliente:</b> Javier Castaneda</li>
				<li class="list-group-item"><b>Correo electrónico:</b> javier55@gmail.com</li>
				<li class="list-group-item"><b>Teléfono:</b> 9331212422</li>
				<li class="list-group-item"><b>Dirección del despacho:</b> Providencia 267, Santiago</li>
				<li class="list-group-item"><b>Pago:</b> $35882</li>
				<li class="list-group-item"><b>Comentario:</b> Sin comentario</li>
				<li class="list-group-item"><b>Estado:</b> Aprobado</li>
			</ul>
		</div>
</div>