<div class="row">
	<div class="col-xs-12">
		<h2 class="text-center">¿Qué necesitas?</h2>
	</div>
	<div class="col-sm-4">
		<h3 class="text-center"><i class="fa fa-cart-arrow-down fa-4x" aria-hidden="true"></i></h3>
		<?php //echo Html::img('prueba.png', 'img de prueba', 'class="logo"') ?>
		<h3 class="text-center"><?php echo Html::link("proveedor/pedidos/$identidad", 'VER PEDIDOS', 'class="btn btn-primary btn-lg" data-toggle="modal"') //proveedor/pedidos/$identidad?></h3>
		<div class="modal fade" id="ver" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
		  <div class="modal-dialog modal-lg" role="document">
		    <div class="modal-content">
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		      </div>
		      <div class="modal-body">
		        <?php echo Html::img('b.png', 'Construcción Uworks', 'class="img-responsive logo"') ?>
		      </div>
		      <div class="modal-footer">
		        <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
		      </div>
		    </div>
		  </div>
		</div>
	</div>
	<div class="col-sm-4">
		<h3 class="text-center"><i class="fa fa-newspaper-o fa-4x" aria-hidden="true"></i></h3>
		<?php //echo Html::img('prueba.png', 'img de prueba', 'class="logo"') ?>
		<h3 class="text-center"><?php echo Html::link("publicaciones/crear/$identidad", 'PUBLICAR', 'class="btn btn-primary btn-lg" data-toggle="modal"') //publicaciones/crear/$identidad ?></h3>
		<div class="modal fade" id="publicar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
		  <div class="modal-dialog modal-lg" role="document">
		    <div class="modal-content">
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		      </div>
		      <div class="modal-body">
		        <?php echo Html::img('c.png', 'Construcción Uworks', 'class="img-responsive logo"') ?>
		      </div>
		      <div class="modal-footer">
		        <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
		      </div>
		    </div>
		  </div>
		</div>
	</div>
	<div class="col-sm-4">
		<h3 class="text-center"><i class="fa fa-hand-peace-o fa-4x" aria-hidden="true"></i></h3>
		<?php //echo Html::img('prueba.png', 'img de prueba', 'class="logo"') ?>
		<h3 class="text-center"><?php echo Html::link("#destacar", 'DESTACAR', 'class="btn btn-primary btn-lg" data-toggle="modal"') ?></h3>
		<div class="modal fade" id="destacar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
		  <div class="modal-dialog modal-lg" role="document">
		    <div class="modal-content">
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		      </div>
		      <div class="modal-body">
		        <?php echo Html::img('d.png', 'Construcción Uworks', 'class="img-responsive logo"') ?>
		      </div>
		      <div class="modal-footer">
		        <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
		      </div>
		    </div>
		  </div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-xs-12">
		<?php //print_r($_SESSION) ?>
	</div>
</div>
