<div class="row">
	<div class="col-sm-2"></div>
	<div class="col-sm-8 col-xs-12">
		<h3 class="text-center">PEDIDOS</h3>
		<div class="table-responsive">
			<table class="table table-bordered">
				<?php if($pedidos == null): ?>
					<div class="panel panel-default">
						<div class="panel-body">
							No posee ningún pedido aún
						</div>
					</div>
				<?php else: ?>
					<tr><th>Fecha</th><th>Nombre</th><th>Total</th><th>Estatus</th><th>Ver detalle</th></tr>
					<?php foreach($pedidos as $valor): ?>
						<tr>
						<td><?php echo $valor->fecha ?></td>
						<td><?php echo $valor->nombre ?></td>
						<td><?php echo $valor->monto ?></td>
						<td><?php echo $valor->estatus ?></td>
						<td><?php echo Html::link("detalles/$id", 'Ver detalle', 'class="btn btn-info"') ?></td>
						</tr>
					<?php endforeach ?>
				<?php endif ?>
			</table>
		</div>
	</div>
	<div class="col-sm-2"></div>
</div>
<div class="row">
    <div class="col-sm-10 col-sm-offset-2 col-xs-12">
			<?php if($pedidos != null): ?>
		<nav>
			<ul class="pagination pagination-lg">
			    <li>
				      <a href="#" aria-label="Previous">
				        <span aria-hidden="true">&laquo;</span>
				      </a>
					    </li>
					    <li><a href="#">1</a></li>
					    <li><a href="#">2</a></li>
					    <li><a href="#">3</a></li>
					    <li><a href="#">4</a></li>
					    <li><a href="#">5</a></li>
					    <li>
				      <a href="#" aria-label="Next">
				        <span aria-hidden="true">&raquo;</span>
				      </a>
			    </li>
			</ul>
		</nav>
	<?php endif ?>
    </div>
</div>
