<div class="row">
	<footer class="footer">
		<div class="col-sm-6">
			<h6 class="text-center"><?php echo date('Y');?> Derechos reservados a UWorks Simple pero rápido</h6>
		</div>
		<div class="col-sm-4 col-sm-offset-2">
			<a href="https://www.facebook.com/uworkschile/" target="_blank"><i class="fa fa-facebook-square fa-2x redes" aria-hidden="true"></i></a> |
			<a href="https://www.linkedin.com/company/uworks?trk=top_nav_home" target="_blank"><i class="fa fa-linkedin-square fa-2x redes redes" aria-hidden="true"></i></a> |
			<a href="https://twitter.com/Uworks_Chile" target="_blank"><i class="fa fa-twitter-square fa-2x redes" aria-hidden="true"></i></a>
		</div>
	</footer>
</div>
