<div class="row">
  <div class="col-xs-12">
    <h3 class="text-center">Restaurar contraseñas del usuario</h3>
  </div>
  <div class="col-sm-3"></div>
  <div class="col-sm-6">
    <?php View::content() ?>
    <?php echo Form::open() ?>
      <div class="well">
        <div class="form-group">
          <label>Ingresar nueva contraseña:</label>
          <?php echo Form::pass('clave', 'class="form-control"') ?>
          <label>Confirmar nueva contraseña:</label>
          <?php echo Form::pass('clave2', 'class="form-control"') ?>
          <br>
          <?php echo Form::submit('Ingresar claves', 'class="btn btn-primary"') ?>
        </div>
      </div>
    <?php echo Form::close() ?>
  </div>
  <div class="col-sm-3"></div>
</div>
