<div class="row">
  <div class="col-xs-12">
    <h3 class="text-center">
      Equipo de trabajo en Uworks
    </h3>
    <h4 class="text-center"><i>
      Somos un equipo multidisciplinario con ansias de hacer del país un mejor lugar.
      Contamos con amplias experiencias en diversos mercados, lo que nos ayuda a entender
      de mejor forma las necesidades de éstos.
    </i></h4>
    <hr>
  </div>
  <br>
</div>
<div class="row">
  <div class="col-sm-3">
    <?php echo Html::img('ana.jpg', 'Fundadora de Uworks', 'class="img-circle logo"') ?>
    <h4 class="text-center">Ana María González</h4>
    <h5 class="text-center">CEO & Founder</h5>
  </div>
  <div class="col-sm-3">
    <?php echo Html::img('guillermo.jpg', 'Líder financiero', 'class="img-circle logo"') ?>
    <h4 class="text-center">Guillermo Candía</h4>
    <h5 class="text-center">Financial Leader</h5>
  </div>
  <div class="col-sm-3">
    <?php echo Html::img('andres.jpg', 'Gestor de ventas', 'class="img-circle logo"') ?>
    <h4 class="text-center">Andrés Valdebenito</h4>
    <h5 class="text-center">Sales Manager</h5>
  </div>
  <div class="col-sm-3">
    <?php echo Html::img('alejandro.jpg', 'Gestor de desarrollo de negocios', 'class="img-circle logo"') ?>
    <h4 class="text-center">Alejandro González</h4>
    <h5 class="text-center">Business Development Manager</h5>
  </div>
</div>
