<div class="row">
	<div class="col-sm-2"></div>
	<div class="col-sm-8">
		<h3 class="text-center">Servicios</h3>
		<p>Proin id mauris nibh. Integer eleifend tellus enim, ac ultrices lectus cursus vel. Sed ultrices, nunc vitae lacinia iaculis, lacus massa molestie erat, vel pretium tellus ipsum sed risus. Nullam tempor elit sapien, vel ultricies ex interdum a. Vestibulum pellentesque ante sed elit tristique, non commodo lorem elementum. Curabitur aliquam commodo ipsum, at pellentesque dui convallis vitae. Mauris a auctor sem.</p>
		<p>Proin id mauris nibh. Integer eleifend tellus enim, ac ultrices lectus cursus vel. Sed ultrices, nunc vitae lacinia iaculis, lacus massa molestie erat, vel pretium tellus ipsum sed risus. Nullam tempor elit sapien, vel ultricies ex interdum a. Vestibulum pellentesque ante sed elit tristique, non commodo lorem elementum. Curabitur aliquam commodo ipsum, at pellentesque dui convallis vitae. Mauris a auctor sem.</p>
	</div>
	<div class="col-sm-2"></div>
</div>