<div class="row">
	<div class="col-xs-12">
		<h3 class="text-center">
			ADMINISTRAR USUARIOS
		</h3>
	</div>
	<div class="col-sm-2"></div>
	<div class="col-sm-8">
		<?php echo Form::openMultipart() ?>
			<div class="form-group">
				<div class="input-group">
			      <input type="file" class="form-control" placeholder="Subir archivo CSV...">
			      <span class="input-group-btn">
			        <?php echo Form::submit(' Subir ', 'class="btn btn-primary glyphicon glyphicon-send"') ?>
			      </span>
			    </div>
			</div>
		<?php echo Form::close() ?>
	</div>
	<div class="col-sm-2"></div>
</div>
<hr>
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<?php echo Form::open('', '', 'class="form-inline"') ?>
			<div class="form-group">
				<?php echo Form::text('nombre', 'class="form-control" placeholder="Nombre y apellido"') ?>
				<?php echo Form::text('correo', 'class="form-control" placeholder="Correo"') ?>
				<?php echo Form::text('telefono', 'class="form-control" placeholder="Teléfono"') ?>
				<?php echo Form::text('comuna', 'class="form-control" placeholder="Comuna"') ?>
				<?php echo Form::text('puntos', 'class="form-control" placeholder="Puntos UWorks"') ?>
				<?php echo Form::submit(' Crear ', 'class="btn btn-primary glyphicon glyphicon-send"') ?>
			</div>
		<?php echo Form::close() ?>
	</div>
</div>
<br>
<div class="row">
	<div class="col-xs-12">
		<div class="table-responsive">
			<table class="table table-bordered">
				<tr>
					<th>Nombre y apellido</th>
					<th>Correo</th>
					<th>Teléfono</th>
					<th>Comuna</th>
					<th>Puntos Uworks</th>
					<th>Acciones</th>
				</tr>
				<tr>
					<td>Pedro Guerrero</td>
					<td>pedrog@gmail.com</td>
					<td>92323131</td>
					<td>Providencia</td>
					<td>340</td>
					<td>
						<?php echo Html::link('empresa/editar', '<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>') ?>
						<?php echo Html::link('empresa/eliminar', '<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>') ?>
					</td>
				</tr>
				<tr>
					<td>Adriana Sayago</td>
					<td>adrianita@gmail.com</td>
					<td>92334232</td>
					<td>Vitacura</td>
					<td>756</td>
					<td>
						<?php echo Html::link("empresa/editar", '<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>') ?>
						<?php echo Html::link("empresa/eliminar", '<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>') ?>
					</td>
				</tr>
			</table>
		</div>
	</div>
</div>
<div class="row">
    <div class="col-xs-12">
		<nav>
			<ul class="pagination pagination-lg">
			    <li>
				      <a href="#" aria-label="Previous">
				        <span aria-hidden="true">&laquo;</span>
				      </a>
					    </li>
					    <li><a href="#">1</a></li>
					    <li><a href="#">2</a></li>
					    <li><a href="#">3</a></li>
					    <li><a href="#">4</a></li>
					    <li><a href="#">5</a></li>
					    <li>
				      <a href="#" aria-label="Next">
				        <span aria-hidden="true">&raquo;</span>
				      </a>
			    </li>
			</ul>
		</nav>
    </div>
</div>