<div class="row">
	<div class="col-xs-12">
		<h2 class="text-center">¿Qué necesitas?</h2>
	</div>
	<div class="col-sm-4">
		<?php echo Html::img('prueba.png', 'img de prueba', 'class="logo"') ?>
		<h3 class="text-center"><?php echo Html::link('empresa/administrar', 'CREAR USUARIOS') ?></h3>
	</div>
	<div class="col-sm-4">
		<?php echo Html::img('prueba.png', 'img de prueba', 'class="logo"') ?>
		<h3 class="text-center"><?php echo Html::link('empresa/comprar', 'COMPRAR PUNTOS') ?></h3>
	</div>
	<div class="col-sm-4">
		<?php echo Html::img('prueba.png', 'img de prueba', 'class="logo"') ?>
		<h3 class="text-center"><?php echo Html::link('empresa/categorias', 'TUS CATEGORIAS') ?></h3>
	</div>
</div>