<div class="row">
	<div class="col-sm-2"></div>
	<div class="col-sm-8">
		<h3 class="text-center">MI PERFIL</h3>
		  <ul class="nav nav-tabs">
		  <li class="active"><a href="#inicio" data-toggle="tab" aria-expanded="true">MIS DATOS</a></li>
		  <li class=""><a href="#profile" data-toggle="tab" aria-expanded="false">MIS COMPRAS</a></li>
		</ul>
		<div id="myTabContent" class="tab-content">
		  <div class="tab-pane fade active in" id="inicio">
		    <ul>
		    	<li>Nombre de la empresa: Hewlett Packard</li>
		    	<li>Correo: administracion@hp.com</li>
		    	<li>Sitio web: www.hp.com</li>
		    	<li>Teléfono: 963231521</li>
		    	<li>Dirección comercial: Providencia 229, Santiago</li>
		    	<li>Comuna: Providencia</li>
		    	<li>Región: Metropolitana</li>
		    	<li>Contraseña: ******</li>
		    </ul>
		  </div>
		  <div class="tab-pane fade" id="profile">
		  <div class="table-responsive">
		    <table class="table table-bordered">
		    	<tr><th>Fecha</th><th>Nombre</th><th>Total</th><th>Estatus</th><th>Ver detalle</th></tr>
		    	<tr>
		    	<td>14-03-2017</td>
		    	<td>Eduardo Carreño</td>
		    	<td>$9342</td>
		    	<td>No facturado</td>
		    	<td><?php echo Html::link('ver', 'Ver detalle', 'class="btn btn-info"') ?></td>
		    	</tr>
		    	<tr>
		    	<td>16-03-2017</td>
		    	<td>Pedro Bastidas</td>
		    	<td>$34588</td>
		    	<td>Facturado</td>
		    	<td><?php echo Html::link('ver', 'Ver detalle', 'class="btn btn-info"') ?></td>
		    	</tr>
		    </table>
		   </div>
		  </div>
		</div>
	</div>
	<div class="col-sm-2"></div>
</div>