<!DOCTYPE html>
<html lang="es">
 <head>
  <meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="shortcut icon" href="/img/icono.ico" />
  <meta name="description" content="Marketplace Chile Uworks" />
  <title>Uworks!</title>
  <?php Tag::css('lumen') ?>
  <?php Tag::css('style') ?>
  <?php Tag::css('awesome') ?>
  <?php Tag::css('uworks') ?>
  <?php echo Html::includeCss() ?>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="<?= PUBLIC_PATH;?>colaborador/"><?php echo Html::img('Logo1.png', 'Colaboradores más contentos', 'class="navbar-brand"') ?></a>
        </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <form class="navbar-form navbar-left busqueda" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Escribe aquí lo que deseas" height="200px">
          </div>
          <button type="submit" class="btn btn-default">Buscar</button>
        </form>
        <ul class="nav navbar-nav navbar-right">
          <?php $item = $items->articulos_total() ?>
          <li><?php echo Html::link('compras/', "Tus compras <span class='glyphicon glyphicon-shopping-cart'></span>") ?></li>
          <li class="dropdown">
          <?php echo Html::link('#', "Bienvenido $nombrep <span class='caret'></span>", 'class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"') ?>
            <ul class="dropdown-menu" role="menu">
              <li><?php echo Html::link("colaborador/perfil/$identidad", 'Mi perfil') ?></li>
              <li><?php echo Html::link("#", "Puntos Uworks: <b><i>$puntos</i></b>") ?></li>
              <li><?php echo Html::link('colaborador/cerrar', 'Cerrar sesión') ?></li>
            </ul>
          </li>
      </ul>
      </div>
    </div>
  </nav>
<div class="container-fluid">
  <?php View::content() ?>
</div>
<div class="container-fluid">
  <?php View::partial('kumbia/pie') ?>
</div>
  <?php echo Tag::js('jquery') ?>
  <?php echo Tag::js('bootstrap') ?>
  <script type="text/javascript">
  $(document).ready(function() {
          $(".enlace").on("click", function(event) {
              var href = $(this).attr('href');
              //alert(href);
              if($("#capa").load(href)){
                alert("Has agregado el articulo al carrito");
                //actualizar();
                event.preventDefault();
              }
          });
      });
  </script>
  <?php echo Tag::js('vue') ?>
  <?php echo Tag::js('puntos') ?>
</body>
</html>
