<div class="row">
	<div class="col-xs-12">
		<h3 class="text-center">
			Mis Publicaciones
		</h3>
	</div>
	<div class="col-sm-2"></div>
	<div class="col-sm-8">
		<?php View::content() ?>
		<div class="table-responsive">
			<table class="table table-bordered">
				<?php if($publicaciones == null): ?>
					<div class="panel panel-default">
						<div class="panel-body">
							No has hecho ninguna publicación
						</div>
					</div>
				<?php endif ?>
				<tr>
					<th>Nombre del producto/servicio</th>
					<th>Fecha y hora</th>
					<th>Precio</th>
					<th>Estatus</th>
					<th>Estado</th>
					<th>Modificar estado</th>
					<th>Acciones</th>
				</tr>
				<?php foreach($publicaciones as $key => $valor): ?>
					<tr>
						<td><?php echo $valor->nombre ?></td>
						<td><?php echo $valor->fecha ?></td>
						<td><?php echo $valor->precio ?></td>
						<td><?php echo $valor->estatus ?></td>
						<td><?php echo $valor->estado ?></td>
						<td>
							<?php echo Html::link("publicaciones/mostrar/$identidad", '<span class="glyphicon glyphicon-play" aria-hidden="true"></span>', 'data-placement="top" data-toggle="tooltip" title="Colocaras tu publicación en línea"') ?>
							<?php echo Html::link("publicaciones/mostrar/$identidad", '<span class="glyphicon glyphicon-pause" aria-hidden="true"></span>', 'data-placement="top" data-toggle="tooltip" title="Pausaras tu publicación"') ?>
						</td>
						<td>
						<?php echo Html::link("publicaciones/ver/$valor->id", '<span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>', 'data-placement="top" data-toggle="tooltip" title="Verás tu publicación"') ?>
						<?php echo Html::link("publicaciones/editar/$valor->id", '<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>', 'data-placement="top" data-toggle="tooltip" title="Editar tu publicación"') ?>
						<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#eliminar<?php echo $valor->id?>"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></button>
						<div class="modal fade" id="eliminar<?php echo $valor->id ?>" tabindex="-1" role="dialog">
								<div class="modal-dialog" role="document">
							    <div class="modal-content">
										<div class="modal-header">
							        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
							        <h4 class="modal-title" id="myModalLabel">¿Estás seguro de eliminar esta publicación?</h4>
							      </div>
										<div class="modal-body">
											<p class="text-justify">Luego de esto no podrás ver su historial
											Si estas seguro elige eliminar, de lo contrario presiona cancelar.</p>
							      </div>
										<div class="modal-footer">
							        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
							        <?php echo Html::link("publicaciones/eliminar/$valor->id", 'Eliminar publicación', 'class="btn btn-danger"') ?>
							      </div>
							    </div>
							  </div>
							</div>
						</td>
					</tr>
				<?php endforeach ?>
			</table>
		</div>
	</div>
	<div class="col-sm-2"></div>
</div>
