<div class="row">
  <div class="col-xs-12">
    <h3 class="text-center">
      Noticias de interés en UWorks
    </h3>
  </div>

</div>
<div class="row">
  <div class="col-xs-12">
    <h4 class="text-center">Titulo del contenido</h4>
  </div>
  <div class="col-sm-2"></div>
  <div class="col-sm-4">
    <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id augue in odio gravida venenatis.
      Aliquam laoreet aliquam pulvinar. Nam neque nulla, fermentum eget ante vitae, vestibulum egestas
      felis. Pellentesque eleifend nisl id commodo condimentum. Nam vel ex efficitur, tristique ante
      ut, sagittis lorem. Morbi euismod, arcu ac facilisis molestie, elit magna tincidunt lorem, et
      sodales ante lacus non diam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices
      posuere cubilia Curae; Lorem ipsum dolor sit amet, consectetur adipiscing elit. Class aptent
      taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse sed
      dui sed velit ullamcorper molestie. Vivamus nec mauris non mauris rhoncus faucibus a ut elit.
      Vivamus fringilla vitae lorem at lobortis. Phasellus cursus libero ac dolor lacinia, sit amet
      feugiat velit dapibus. Curabitur nec facilisis quam.
    </p>
  </div>
  <div class="col-sm-4">
    <?php echo Html::img('placeholder.png', 'Imagenes de noticias UWorks', 'class="img-rounded"') ?>
  </div>
  <div class="col-sm-2"></div>
</div>
